---
name: Publish (npm)
on:
    push: ~

jobs:
    deploy:
        name: 'Publish to npm'
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
              node-version: '10.x'
              registry-url: 'https://registry.npmjs.org'
        - run: npm install
        - if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
          env:
              NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          run: npm publish

